// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCujd3_8UFapF6IOL_SIi4-Ni8tVY-bjOY',
    appId: '1:399001433958:web:6674efdac7d4fa82143aa7',
    messagingSenderId: '399001433958',
    projectId: 'untoggl',
    authDomain: 'untoggl.firebaseapp.com',
    storageBucket: 'untoggl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx8AqTEUiIdc89e6rULlRvIoeRStTEtXU',
    appId: '1:399001433958:android:123b003de68b07ab143aa7',
    messagingSenderId: '399001433958',
    projectId: 'untoggl',
    storageBucket: 'untoggl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoFnoD83oB9rhXjIm6wxtxHrxCBPkKSCg',
    appId: '1:399001433958:ios:d89c17657ea02a00143aa7',
    messagingSenderId: '399001433958',
    projectId: 'untoggl',
    storageBucket: 'untoggl.appspot.com',
    iosBundleId: 'com.example.untoggl',
  );
}
